--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrEcstsy/DropPackages
build-by-default: true
branches:
- main
projects:
  DropPackages:
    path: ""
    libs:
      - src: "Paroxity/Commando/Commando"
        version: "^3.2.0"
      - src: "muqsit/InvMenu/InvMenu"
        branch: "pm5"
        version: "^4.6.3"
...
